/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controladores.BusG;
import Modelos.Bus;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Controladores.ConexionBD;
import java.sql.Connection;
import Controladores.RecorridoG;
import Modelos.Recorrido;
import Modelos.RecorridoBD;



/**
 *
 * @author diego
 */
public class Buses extends javax.swing.JInternalFrame {

    /**
     * Creates new form Buses
     */
    public ConexionBD conexion;
    public Connection link;
    public Buses() {
        initComponents();
        
        conexion=new ConexionBD();
        link=conexion.Conectar();
        
        CargarRecorridos();
    }

    
    public void CargarRecorridos(){
        
        ArrayList<Recorrido>Lista=new ArrayList<Recorrido>();
        RecorridoG Listarecorrido=new RecorridoG();
        Lista=Listarecorrido.Leer(link);
         for(int i=0;i<Lista.size();i++){
            Recorrido recorrido=new Recorrido(Lista.get(i).getNumeroRecorrido(),Lista.get(i).getNombreRecorrido());
            cambiarRecorrido.addItem(String.valueOf(Lista.get(i).getNombreRecorrido()));
        }
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtPatenteBus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoraTermino = new javax.swing.JTextField();
        GuardarBus = new javax.swing.JButton();
        ModificarBus = new javax.swing.JButton();
        EliminarBus = new javax.swing.JButton();
        BuscarBus = new javax.swing.JButton();
        cambiarRecorrido = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cambiarDia = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Patente Bus");

        jLabel2.setText("Recorrido a asignar");

        jLabel3.setText("Hora Inicio");

        jLabel4.setText("Hora Termino");

        txtHoraTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraTerminoActionPerformed(evt);
            }
        });

        GuardarBus.setText("Guardar Bus");
        GuardarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBusActionPerformed(evt);
            }
        });

        ModificarBus.setText("Actualizar Bus Actual");
        ModificarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBusActionPerformed(evt);
            }
        });

        EliminarBus.setText("Eliminar Bus Actual");
        EliminarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBusActionPerformed(evt);
            }
        });

        BuscarBus.setText("Buscar Bus");
        BuscarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBusActionPerformed(evt);
            }
        });

        cambiarRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRecorridoActionPerformed(evt);
            }
        });

        jLabel5.setText("Dia de la Semana");

        cambiarDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Asignar", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarBus, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtPatenteBus)
                    .addComponent(cambiarRecorrido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(BuscarBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(EliminarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoraTermino)
                    .addComponent(cambiarDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatenteBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cambiarRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GuardarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cambiarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ModificarBus)
                .addGap(18, 18, 18)
                .addComponent(EliminarBus)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraTerminoActionPerformed

    private void ModificarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBusActionPerformed
        // TODO add your handling code here:
        BusG bus=new BusG();
        Bus ConsultaBus=new Bus();
        
        if(!txtPatenteBus.getText().equals("")){
            ConsultaBus=bus.Buscar(link,txtPatenteBus.getText());
            JOptionPane.showMessageDialog(null, "");
            
        }else{
             JOptionPane.showMessageDialog(null, "Coloque una patente valida");
        }
        
        ConsultaBus.setHoraInicio(Integer.valueOf(txtHoraInicio.getText()));
        ConsultaBus.setHoraTermino(Integer.valueOf(txtHoraTermino.getText()));
        ConsultaBus.setDiaSemana(cambiarDia.getSelectedItem().toString());
        ConsultaBus.setPatenteBus(txtPatenteBus.getText());
        ConsultaBus.setNombreRecorrido(cambiarRecorrido.getSelectedItem().toString());
        
        if(bus.Actualizar(link,ConsultaBus)){
            JOptionPane.showMessageDialog(null, "Datos Modificados!");
        }else{
            JOptionPane.showMessageDialog(null,"Los datos no fueron modificados");
        }

    }//GEN-LAST:event_ModificarBusActionPerformed

    private void EliminarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBusActionPerformed
        // TODO add your handling code here:
        BusG bus=new BusG();
        Bus ConsultaBus=new Bus();
        ConsultaBus.setPatenteBus(txtPatenteBus.getText());
        
        if(bus.Crear(link,ConsultaBus)){
            JOptionPane.showMessageDialog(null, "Datos Eliminados!");
        }else{
            JOptionPane.showMessageDialog(null,"Los datos no fueron eliminados");
        }

                      
    
    }//GEN-LAST:event_EliminarBusActionPerformed

    private void BuscarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBusActionPerformed
        // TODO add your handling code here:
        
        BusG bus=new BusG();
        Bus ConsultaBus=new Bus();
   
        if(!txtPatenteBus.getText().equals("")){
            ConsultaBus=bus.Buscar(link,txtPatenteBus.getText());
            JOptionPane.showMessageDialog(null, "");
            
        }else{
             JOptionPane.showMessageDialog(null, "Coloque una patente valida");
        }
       
        
        txtHoraInicio.setText(String.valueOf(ConsultaBus.getHoraInicio()));
        txtHoraTermino.setText(String.valueOf(ConsultaBus.getHoraTermino()));
        cambiarDia.setSelectedItem(ConsultaBus.getDiaSemana());
        txtPatenteBus.setText(ConsultaBus.getPatenteBus());
        cambiarRecorrido.setSelectedItem(String.valueOf(ConsultaBus.getNombreRecorrido()));
        
        
        
        
    }//GEN-LAST:event_BuscarBusActionPerformed

    private void GuardarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBusActionPerformed
        // TODO add your handling code here:
        BusG bus=new BusG();
        Bus ConsultaBus=new Bus();

        ConsultaBus.setHoraInicio(Integer.valueOf(txtHoraInicio.getText()));
        ConsultaBus.setHoraTermino(Integer.valueOf(txtHoraTermino.getText()));
        ConsultaBus.setDiaSemana(cambiarDia.getSelectedItem().toString());
        ConsultaBus.setPatenteBus(txtPatenteBus.getText());
        ConsultaBus.setNombreRecorrido(cambiarRecorrido.getSelectedItem().toString());

        if(bus.Crear(link,ConsultaBus)){
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,"Datos Creados!");
        }
         
    }//GEN-LAST:event_GuardarBusActionPerformed

    private void cambiarRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRecorridoActionPerformed

    }//GEN-LAST:event_cambiarRecorridoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBus;
    private javax.swing.JButton EliminarBus;
    private javax.swing.JButton GuardarBus;
    private javax.swing.JButton ModificarBus;
    private javax.swing.JComboBox<String> cambiarDia;
    private javax.swing.JComboBox<String> cambiarRecorrido;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtHoraTermino;
    private javax.swing.JTextField txtPatenteBus;
    // End of variables declaration//GEN-END:variables
}
